# Generated by Django 2.1.4 on 2019-01-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTransData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BestTrans Sp z o.o', max_length=64)),
                ('tax_number', models.CharField(default='123 456 78 90', max_length=64)),
                ('street', models.CharField(default='ul. Piotrkowska 102', max_length=64)),
                ('post_code', models.CharField(default='90-010 Łódź', max_length=64)),
                ('place', models.CharField(default='Łódź', max_length=64)),
                ('country', models.CharField(default='Poland', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapping', models.CharField(default='', max_length=64)),
                ('pallets_number', models.IntegerField()),
                ('additional_remarks', models.TextField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('card_drive_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hour', models.TimeField()),
                ('name', models.CharField(default='', max_length=32)),
                ('remarks', models.TextField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallets_number', models.IntegerField()),
                ('additional_remarks', models.TextField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_destination_place_offer', to='api.ExtendAddress')),
                ('loading_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_loading_place_offer', to='api.ExtendAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_remarks', models.TextField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('cargo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('tax_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('post_code', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('registration_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_destination_place_order', to='api.ExtendAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ManyToManyField(to='api.Driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='loading_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_loading_place_order', to='api.ExtendAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.BestTransData'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='offer',
            name='vehicle',
            field=models.ManyToManyField(to='api.Vehicle'),
        ),
        migrations.AddField(
            model_name='extendaddress',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SimpleAddress'),
        ),
    ]
