# Generated by Django 2.1.4 on 2019-01-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190107_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ManyToManyField(blank=True, null=True, to='api.Driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ManyToManyField(blank=True, null=True, to='api.Vehicle'),
        ),
    ]
